spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jwtdemo # Docker Compose создаст сеть, в которой 'postgres' будет направлять к контейнеру БД.
    username: postgres
    password: 809765
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
